/*
 * AddJudge.java
 *
 * Created on 2008年8月9日, 下午5:02
 */

package com.Exam.controller;

import javax.swing.JOptionPane;

import com.Exam.bean.*;
import com.Exam.dao.FindQuestionDao;

/**
 *
 * @author  Administrator
 */
public class AddJudge extends javax.swing.JFrame {// 增加判断

    /** Creates new form AddJudge */
    public AddJudge() { // 构造方法
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {// 初始化方法

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addJudgejLabel = new javax.swing.JLabel();
        idCountjLabel = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        idCountjLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NamejTextArea = new javax.swing.JTextArea();
        answerJLabel = new javax.swing.JLabel();
        answerjTextField1 = new javax.swing.JTextField();
        addjButton = new javax.swing.JButton();
        resjButton = new javax.swing.JButton();
        resjButton1 = new javax.swing.JButton();
        remarkLabel = new javax.swing.JLabel();
        remarkjTextField = new javax.swing.JTextField();
        jLabel1.setText("");
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {// 关闭窗口监听方法
                formWindowClosing(evt);
            }
        });
        setTitle("添加判断题");
        addJudgejLabel.setText("添加判断题模块：");
        idCountjLabel.setText("试题编号：");
        FindQuestionDao findDao = new FindQuestionDao();
  
        int id = findDao.findQMid();
        
        idjTextField.setText(""+(id+1));
        idjTextField.setEditable(false);
        idCountjLabel1.setText("试题题目：");
        NamejTextArea.setColumns(20);
        NamejTextArea.setRows(5);
        jScrollPane1.setViewportView(NamejTextArea);
        answerJLabel.setText("试题答案：");
        answerjTextField1.setText("");
        addjButton.setText("添加");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        resjButton.setText("重置");
        resjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resjButtonActionPerformed(evt);
            }
        });

        resjButton1.setText("关闭");
        resjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resjButton1ActionPerformed(evt);
            }
        });
        remarkLabel.setText("   备 注：");
        remarkjTextField.setText("");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(addJudgejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(addjButton)
                .addGap(18, 18, 18)
                .addComponent(resjButton)
                .addGap(18, 18, 18)
                .addComponent(resjButton1)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(remarkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remarkjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idCountjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idCountjLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(answerJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerjTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJudgejLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCountjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCountjLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerJLabel)
                    .addComponent(answerjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remarkLabel)
                    .addComponent(remarkjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addjButton)
                    .addComponent(resjButton)
                    .addComponent(resjButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }

private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {
	if(NamejTextArea.getText().equals("")){
		JOptionPane.showMessageDialog(this,"试题题目不能为空！","信息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	if(answerjTextField1.getText().equals("")){
		JOptionPane.showMessageDialog(this,"试题答案不能为空！","信息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	if(!(answerjTextField1.getText().equals("正确"))&&!(answerjTextField1.getText().equals("错误"))){
		JOptionPane.showMessageDialog(this,"试题答案只能是‘正确’或‘错误’两种！","消息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	Question question = new Question();
	question.setId(Integer.parseInt(idjTextField.getText()));
	FindQuestionDao findQuestion = new FindQuestionDao();
	QuestionType qtype = new QuestionType();
	qtype.setQName("判断题");
	QuestionType questype = findQuestion.getQuestionTypeID(qtype);
	question.setTypeid(questype.getId());
	question.setQ_subject(ChDeal.toISO(NamejTextArea.getText()));
	question.setQ_answer(ChDeal.toISO(answerjTextField1.getText()));
	question.setOptionA("");
	question.setOptionB("");
	question.setOptionC("");
	question.setOptionD("");
	System.out.println("sssssssssssssssssssss "+remarkjTextField.getText());
	question.setNote(remarkjTextField.getText());
	boolean bool = findQuestion.setQuestionDBbean(question);
	if(bool == true){
		JOptionPane.showMessageDialog(this,"判断题添加成功！","信息对话框",JOptionPane.WARNING_MESSAGE);
		dispose();
		ControllerFrame cont = new ControllerFrame();
        cont.setVisible(true);
	}
}
private void resjButtonActionPerformed(java.awt.event.ActionEvent evt) {
	NamejTextArea.setText("");
	answerjTextField1.setText("");
	remarkjTextField.setText("");
}

private void resjButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	dispose();
	ControllerFrame controller = new ControllerFrame();
	controller.setVisible(true);
	controller.setBounds(100, 200, 650, 450);
}
private void formWindowClosing(java.awt.event.WindowEvent evt) {
	dispose();
	ControllerFrame controll = new ControllerFrame();
	controll.setVisible(true);
}
    /**
    * @param args the command line arguments
    */
   
    private javax.swing.JTextArea NamejTextArea;
    private javax.swing.JLabel addJudgejLabel;
    private javax.swing.JButton addjButton;
    private javax.swing.JLabel answerJLabel;
    private javax.swing.JTextField answerjTextField1;
    private javax.swing.JLabel idCountjLabel;
    private javax.swing.JLabel idCountjLabel1;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remarkLabel;
    private javax.swing.JTextField remarkjTextField;
    private javax.swing.JButton resjButton;
    private javax.swing.JButton resjButton1;
 }
