/*
 * ControllerFrame.java
 *
 * Created on 2008年8月7日, 下午2:41
 */

package com.Exam.controller;

import java.io.File;
import java.security.UnresolvedPermission;
import java.util.ArrayList;
import javax.swing.GroupLayout;

import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;

import com.Exam.bean.*;
import com.Exam.dao.FindGrade;

/**
 * 
 * @author Administrator
 */
public class ControllerFrame extends javax.swing.JFrame {// 主控制窗体

	/** Creates new form ControllerFrame */
	public ControllerFrame() {// 构造方法
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {// 初始化方法
		jPanel1 = new javax.swing.JPanel();
		messageLabel = new javax.swing.JLabel();
		messageJchock = new javax.swing.JComboBox();
		ifLabel = new javax.swing.JLabel();
		nameTextField = new javax.swing.JTextField();
		findButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		addquestion = new javax.swing.JButton();
		addUserButton = new javax.swing.JButton();
		closeButton = new javax.swing.JButton();
		jSeparator1 = new javax.swing.JSeparator();
		downmessage = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		superControll = new javax.swing.JMenu();
		addMenu = new javax.swing.JMenu();
		addradioItem = new javax.swing.JMenuItem();
		addmoreItem = new javax.swing.JMenuItem();
		addjubje = new javax.swing.JMenuItem();
		updateMenu = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		userManager = new javax.swing.JMenuItem();
		findGrade = new javax.swing.JMenuItem();
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		messageLabel.setText("查询条件：");
		messageJchock.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "考生号", "考生姓名" }));
		ifLabel.setText("查询值：");
		nameTextField.setText("");
		findButton.setText("查询");
		findButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				findButtonActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(

		new Object[][] {}, new String[] { "考生编号", "考生姓名", "单选题得分", "多选题得分",
				"判断题得分", "总分", "考试时间" }

		));
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		FindGrade findGradebean = new FindGrade();
		java.util.List list = findGradebean.findGrade();// 把获取的所有学分用户放入list
		setTitle("后台管理");
		if (!list.isEmpty()) {
			for (int j = 0; j < list.size(); j++) {
				Grade grade = (Grade) list.get(j);
				model.addRow(new Object[] {// 添加所有学分用户
						grade.getId(), ChDeal.toChinese(grade.getUserName()),
								grade.getRadioResult(), grade.getFullResule(),
								grade.getEsitResult(), grade.getBatsisResult(),
								ChDeal.toChinese(grade.getDate()) });
			}
		}
		jScrollPane1.setViewportView(jTable1);
		addquestion.setText("添加试题");
		addquestion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addquestionActionPerformed(evt);
			}
		});

		addUserButton.setText("添加用户");
		addUserButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addUserButtonActionPerformed(evt);
			}
		});

		closeButton.setText("退出");
		closeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeButtonActionPerformed(evt);
			}
		});

		downmessage.setText("物联网1202班————胡松");


		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
			.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
				.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
					.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(
							GroupLayout.Alignment.LEADING).addComponent(jSeparator1,GroupLayout.DEFAULT_SIZE,596,Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING,false)
									.addComponent(addUserButton,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
									.addComponent(addquestion,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
									.addComponent(closeButton,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE))
									.addGap(12,12,12).addGroup(jPanel1Layout.createParallelGroup(
																																GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jScrollPane1,
																																GroupLayout.Alignment.TRAILING,
																																GroupLayout.DEFAULT_SIZE,
																																498,
																																Short.MAX_VALUE)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				messageLabel)
																																		.addPreferredGap(
																																				LayoutStyle.ComponentPlacement.RELATED,
																																				GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				messageJchock,
																																				GroupLayout.PREFERRED_SIZE,
																																				92,
																																				GroupLayout.PREFERRED_SIZE)
																																		.addPreferredGap(
																																				LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				ifLabel)
																																		.addPreferredGap(
																																				LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				nameTextField,
																																				GroupLayout.PREFERRED_SIZE,
																																				137,
																																				GroupLayout.PREFERRED_SIZE)
																																		.addGap(
																																				18,
																																				18,
																																				18)
																																		.addComponent(
																																				findButton,
																																				GroupLayout.PREFERRED_SIZE,
																																				67,
																																				GroupLayout.PREFERRED_SIZE)
																																		.addGap(
																																				31,
																																				31,
																																				31)))))
																		.addContainerGap())
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												10,
																												10,
																												10)
																										.addComponent(
																												jLabel1,
																												GroupLayout.PREFERRED_SIZE,
																												195,
																												GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								downmessage,
																								GroupLayout.PREFERRED_SIZE,
																								287,
																								GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				135,
																				135,
																				135)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																GroupLayout.Alignment.BASELINE)
														.addComponent(ifLabel)
														.addComponent(
																messageJchock,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																messageLabel)
														.addComponent(
																nameTextField,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																findButton))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				33,
																				33,
																				33)
																		.addComponent(
																				addquestion)
																		.addGap(
																				43,
																				43,
																				43)
																		.addComponent(
																				addUserButton)
																		.addGap(
																				42,
																				42,
																				42)
																		.addComponent(
																				closeButton))
														.addComponent(
																jScrollPane1,
																GroupLayout.PREFERRED_SIZE,
																264,
																GroupLayout.PREFERRED_SIZE))
										.addGap(8, 8, 8)
										.addComponent(jSeparator1,
												GroupLayout.PREFERRED_SIZE, 10,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(downmessage)
										.addPreferredGap(
												LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel1).addContainerGap(
												GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		superControll.setText("题库管理");

		addMenu.setText("增加考题");
		addMenu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addMenuActionPerformed(evt);
			}
		});
		addradioItem.setText("增加单选题");
		addMenu.add(addradioItem);
		addradioItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addradioItemActionPerformed(evt);
			}
		});
		addmoreItem.setText("增加多选题");
		addmoreItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addmoreItemActionPerformed(evt);
			}
		});
		addMenu.add(addmoreItem);
		addjubje.setText("增加判断题");
		addjubje.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addjubjeActionPerformed(evt);
			}
		});
		addMenu.add(addjubje);
		superControll.add(addMenu);
		updateMenu.setText("修改/删除考题");

		updateMenu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateMenuActionPerformed(evt);
			}
		});
		superControll.add(updateMenu);

		jMenuBar1.add(superControll);

		jMenu2.setText("系统管理");

		userManager.setText("用户管理");
		userManager.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userManagerActionPerformed(evt);
			}
		});
		jMenu2.add(userManager);

		findGrade.setText("参数设置");
		findGrade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				findGradeActionPerformed(evt);
			}
		});
		jMenu2.add(findGrade);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addComponent(jPanel1,
				GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 620,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addComponent(jPanel1,
				GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		getContentPane().setLayout(layout);
		pack();
	}

	private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {
		boolean flag = false;// 没查询到为true;否则为false
		// 首先判断用户是否输入查询值
		if (nameTextField.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "请输入查询条件", "消息对话框",JOptionPane.WARNING_MESSAGE);
			return; // 如果有没有输入查询值 返回
		}
		// 如果用户选择按“考生号”查询考分，系统将调用getGradeID()方法，并将查询结果显示在窗体中
		if (messageJchock.getSelectedItem().toString().equals("考生号")) {
			FindGrade findGrade = new FindGrade();
			java.util.List<Grade> gradeList = findGrade.findGrade();
			if (!gradeList.isEmpty()) {
				for (int i = 0; i < gradeList.size(); i++) {
					Grade grade = gradeList.get(i);
					try {
						if (grade.getId() != Integer.parseInt(nameTextField
								.getText())) {
						}
					} catch (Exception e) {
						JOptionPane.showMessageDialog(this, "必须输入数字！", "信息对话框",
								JOptionPane.WARNING_MESSAGE);
						return;
					}
					if (grade.getId() == Integer.parseInt(nameTextField
							.getText())) {
						Grade gradeId = findGrade.getGradeID(grade);
						if (gradeId != null) {
							((DefaultTableModel) jTable1.getModel())
									.setRowCount(0);
							((DefaultTableModel) jTable1.getModel())
									.addRow(new Object[] {
											grade.getId(),
											ChDeal.toChinese(grade
													.getUserName()),
											grade.getRadioResult(),
											grade.getFullResule(),
											grade.getEsitResult(),
											grade.getBatsisResult(),
											ChDeal.toChinese(grade.getDate()) });
							flag = false;
							return;
						}
					} else {
						flag = true;
					}
				}
				if (flag) {
					JOptionPane.showMessageDialog(this, "没有要查询的考生成绩！", "信息对话框",
							JOptionPane.WARNING_MESSAGE);
				}
			}
		}

		if (messageJchock.getSelectedItem().toString().equals("考生姓名")) {
			FindGrade findGrade = new FindGrade();
			Grade grade = new Grade();
			grade.setUserName(nameTextField.getText());
			Grade grage = findGrade.getGradeName(grade);

			if ((grade.getUserName().equals(nameTextField.getText()))
					&& (grage.getId() != 0)) {
				((DefaultTableModel) jTable1.getModel()).setRowCount(0);
				((DefaultTableModel) jTable1.getModel()).addRow(new Object[] {
						grage.getId(), grage.getUserName(),
						grage.getRadioResult(), grage.getFullResule(),
						grage.getEsitResult(), grage.getBatsisResult(),
						ChDeal.toChinese(grage.getDate()) });
			} else {
				JOptionPane.showMessageDialog(this, "没有要查询的考生成绩！", "信息对话框",
						JOptionPane.WARNING_MESSAGE);
			}
		}
	}

	private void addquestionActionPerformed(java.awt.event.ActionEvent evt) {
		TestFrame testFrame = new TestFrame();
		testFrame.setVisible(true);
		testFrame.setBounds(200, 150, 500, 500);
		testFrame.setTitle("添加考题");
		this.setVisible(false);
	}

	private void updateMenuActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		UpdateFrame updateFrame = new UpdateFrame();
		updateFrame.setVisible(true);
		updateFrame.setBounds(100, 150, 630, 350);
	}

	private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		AddFrame addUser = new AddFrame();
		addUser.setVisible(true);
		addUser.setBounds(200, 200, 400, 300);
		addUser.setTitle("添加用户对话框");
	}

	private void findGradeActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		UpdateExamParameter updateExam = new UpdateExamParameter();
		updateExam.setVisible(true);
		updateExam.setBounds(200, 150, 500, 330);
	}

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		int n = JOptionPane.showConfirmDialog(this, "确定要退出系统吗？", "确定对话框",
				JOptionPane.YES_NO_OPTION);
		if (n == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
		if (n == JOptionPane.NO_OPTION) {

		}
	}

	private void addMenuActionPerformed(java.awt.event.ActionEvent evt) {

	}

	private void addradioItemActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		AddRadioFrame addRadioFrame = new AddRadioFrame();
		addRadioFrame.setVisible(true);
		addRadioFrame.setBounds(200, 100, 400, 500);
	}

	private void addmoreItemActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		AddMoreFrame addMoreFrame = new AddMoreFrame();
		addMoreFrame.setVisible(true);
		addMoreFrame.setBounds(200, 100, 400, 500);
	}

	private void addjubjeActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		AddJudge addjudge = new AddJudge();
		addjudge.setVisible(true);
		addjudge.setBounds(200, 150, 400, 350);
	}

	private void userManagerActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
		UserAddFrame userAdd = new UserAddFrame();
		userAdd.setVisible(true);
		userAdd.setBounds(200, 200, 425, 330);
	}

	private javax.swing.JMenu addMenu;
	private javax.swing.JButton addUserButton;
	private javax.swing.JMenuItem addjubje;
	private javax.swing.JMenuItem addmoreItem;
	private javax.swing.JButton addquestion;
	private javax.swing.JMenuItem addradioItem;
	private javax.swing.JButton closeButton;
	private javax.swing.JLabel downmessage;
	private javax.swing.JButton findButton;
	private javax.swing.JMenuItem findGrade;
	private javax.swing.JLabel ifLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JComboBox messageJchock;
	private javax.swing.JLabel messageLabel;
	private javax.swing.JMenu superControll;
	private javax.swing.JMenuItem updateMenu;
	private javax.swing.JMenuItem userManager;
}
