/*
 * testFrame.java
 *
 * Created on 2008年8月8日, 上午8:30
 */

package com.Exam.controller;

import javax.swing.JOptionPane;

import com.Exam.bean.*;
import com.Exam.dao.FindQuestionDao;

/**
 *
 * @author  Administrator
 */
public class TestFrame extends javax.swing.JFrame {

    /** Creates new form testFrame */
    public TestFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        noteTextField = new javax.swing.JPanel();
        testQuestionMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        qSubjectjTextArea = new javax.swing.JTextArea();
        testQuestionId = new javax.swing.JLabel();
        qidjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        qTypejComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        answerMessage = new javax.swing.JLabel();
        optionA = new javax.swing.JLabel();
        optionTextField = new javax.swing.JTextField();
        optionB = new javax.swing.JLabel();
        optionBTextField = new javax.swing.JTextField();
        optionC = new javax.swing.JLabel();
        optionCjTextField = new javax.swing.JTextField();
        optionD = new javax.swing.JLabel();
        optionDTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        answermessage = new javax.swing.JLabel();
        qanswerTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();
        noteMessage = new javax.swing.JLabel();
        noteField = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        testQuestionMessage.setText("试题题目：");
        qSubjectjTextArea.setColumns(20);
        qSubjectjTextArea.setRows(5);
        jScrollPane1.setViewportView(qSubjectjTextArea);
testQuestionId.setText("试题编号：");
int id = 0;
FindQuestionDao findQuestion = new FindQuestionDao();
java.util.List<Question> questList = findQuestion.findQuestion();
if(questList.size()>0){
	for(int i = 0;i<questList.size();i++){
		Question question = questList.get(i);
		id = question.getId();
	}
}
int ids = findQuestion.findQMid();
int qid = ids+1;
qidjTextField.setText(""+qid);
qidjTextField.setEnabled(false);
        jLabel1.setText("试题类型：");
        qTypejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "单选题", "多选题", "" +
        		"判断题"}));
        answerMessage.setText("题目选项部分，如果是判断题该部分内容可以省略：");

        optionA.setText("A：");

        optionTextField.setText("");

        optionB.setText("B：");

        optionBTextField.setText("");

        optionC.setText("C：");

        optionCjTextField.setText("");

        optionD.setText("D：");

        optionDTextField.setText("");

        answermessage.setText(" 答  案：");

        qanswerTextField.setText("");

        saveButton.setText("保存");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("重置");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        noteMessage.setText(" 备  注：");

        noteField.setText("");

        javax.swing.GroupLayout noteTextFieldLayout = new javax.swing.GroupLayout(noteTextField);
        noteTextField.setLayout(noteTextFieldLayout);
        noteTextFieldLayout.setHorizontalGroup(
            noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noteTextFieldLayout.createSequentialGroup()
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noteTextFieldLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(testQuestionId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qidjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addComponent(testQuestionMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215))))
                    .addGroup(noteTextFieldLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addComponent(optionB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(optionBTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addComponent(optionA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(optionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addComponent(optionC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(optionCjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addComponent(optionD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(optionDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(noteTextFieldLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(answerMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(noteTextFieldLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addComponent(noteMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noteField, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                            .addGroup(noteTextFieldLayout.createSequentialGroup()
                                .addComponent(answermessage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qanswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(saveButton)
                                .addGap(18, 18, 18)
                                .addComponent(canceljButton)))))
                .addContainerGap())
        );
        noteTextFieldLayout.setVerticalGroup(
            noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noteTextFieldLayout.createSequentialGroup()
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testQuestionId))
                .addGap(9, 9, 9)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testQuestionMessage)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qTypejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionB)
                    .addComponent(optionBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionC)
                    .addComponent(optionCjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionD)
                    .addComponent(optionDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteMessage)
                    .addComponent(noteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(noteTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qanswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answermessage)
                    .addComponent(saveButton)
                    .addComponent(canceljButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }
private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
	if(qSubjectjTextArea.getText().equals("")){
		JOptionPane.showMessageDialog(this, "请输入考试题目", "信息对话框",JOptionPane.WARNING_MESSAGE);
		return;
	}
	if(qanswerTextField.getText().equals("")){
		JOptionPane.showMessageDialog(this, "请输入考题答案","信息对话框", JOptionPane.WARNING_MESSAGE);
		return;
	}
	if((qTypejComboBox.getSelectedItem().toString().equals("多选题"))
			&&(qanswerTextField.getText().length()>0)
			&&(qanswerTextField.getText().indexOf(",")==-1)){
		JOptionPane.showMessageDialog(this, "多选题的答案要求格式如：'A,B,C,D'", "信息对话框", JOptionPane.WARNING_MESSAGE);
		return;
	}
	if(qTypejComboBox.getSelectedItem().toString().equals("判断题")){
		if(!(qanswerTextField.getText().equals("正确"))&&!(qanswerTextField.getText().equals("错误"))){
			JOptionPane.showMessageDialog(this,"试题答案只能是‘正确’或‘错误’两种！","消息对话框",JOptionPane.WARNING_MESSAGE);
			return;
		}
	}
	Question question = new Question();
	question.setId(Integer.parseInt(qidjTextField.getText()));
	FindQuestionDao insertQuestion = new FindQuestionDao();
	QuestionType questionType = new QuestionType();
	questionType.setQName(ChDeal.toISO(qTypejComboBox.getSelectedItem().toString()));
	QuestionType qtype = insertQuestion.getQuestionType(questionType);	
	question.setTypeid(qtype.getId());	
	question.setQ_subject(ChDeal.toISO(qSubjectjTextArea.getText()));
	question.setQ_answer(ChDeal.toISO(qanswerTextField.getText().trim()));
	question.setOptionA(ChDeal.toISO(optionTextField.getText()));
	question.setOptionB(ChDeal.toISO(optionBTextField.getText()));
	question.setOptionC(ChDeal.toISO(optionCjTextField.getText()));
	question.setOptionD(ChDeal.toISO(optionDTextField.getText()));
	question.setNote(ChDeal.toISO(noteField.getText()));	
	insertQuestion.setQuestionDBbean(question);
	int n = JOptionPane.showConfirmDialog(this, "确定输入的数据正确吗啊？", "信息对话框", JOptionPane.YES_NO_OPTION);
	if(n == JOptionPane.YES_OPTION){
	JOptionPane.showMessageDialog(this, "考题添加成功", "信息对话框",JOptionPane.WARNING_MESSAGE);
	dispose();
	ControllerFrame con = new ControllerFrame();
	con.setVisible(true);
	}	
}
private void formWindowClosed(java.awt.event.WindowEvent evt) {
	dispose();
	ControllerFrame controllFrame = new ControllerFrame();
	controllFrame.setVisible(true);
}
private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {
	qSubjectjTextArea.setText("");
	qanswerTextField.setText("");
	optionTextField.setText("");
	optionBTextField.setText("");
	optionCjTextField.setText("");
	optionDTextField.setText("");
	noteField.setText("");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answerMessage;
    private javax.swing.JLabel answermessage;
    private javax.swing.JButton canceljButton;
    private javax.swing.JComboBox qTypejComboBox;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea qSubjectjTextArea;
    private javax.swing.JTextField qidjTextField;
    private javax.swing.JTextField qanswerTextField;
    private javax.swing.JTextField noteField;
    private javax.swing.JLabel noteMessage;
    private javax.swing.JPanel noteTextField;
    private javax.swing.JLabel optionA;
    private javax.swing.JLabel optionB;
    private javax.swing.JTextField optionBTextField;
    private javax.swing.JLabel optionC;
    private javax.swing.JTextField optionCjTextField;
    private javax.swing.JLabel optionD;
    private javax.swing.JTextField optionDTextField;
    private javax.swing.JTextField optionTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel testQuestionId;
    private javax.swing.JLabel testQuestionMessage;
    // End of variables declaration//GEN-END:variables

}
