/*
 * UpdateExamParameter.java
 *
 * Created on 2008年8月12日, 上午8:52
 */

package com.Exam.controller;

import javax.swing.JOptionPane;

import com.Exam.bean.Stat;
import com.Exam.dao.FindStat;

/**
 *
 * @author  Administrator
 */
public class UpdateExamParameter extends javax.swing.JFrame {

    /** Creates new form UpdateExamParameter */
    public UpdateExamParameter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioBL = new javax.swing.JLabel();
        radiojComboBox = new javax.swing.JComboBox();
        messageJLabel = new javax.swing.JLabel();
        moreBL1 = new javax.swing.JLabel();
        morejComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        judgeBL = new javax.swing.JLabel();
        judgeJComboBox = new javax.swing.JComboBox();
        signJLabel = new javax.swing.JLabel();
        examTime = new javax.swing.JLabel();
        examTimejTextField = new javax.swing.JTextField();
        minutejLabel = new javax.swing.JLabel();
        radiojLabel = new javax.swing.JLabel();
        radioMarkjComboBox = new javax.swing.JComboBox();
        morejLabel = new javax.swing.JLabel();
        moreMarkjComboBox = new javax.swing.JComboBox();
        judgejLabel = new javax.swing.JLabel();
        judgeMarkjComboBox1 = new javax.swing.JComboBox();
        messagejLabel = new javax.swing.JLabel();
        okjButton = new javax.swing.JButton();
        resetjButton = new javax.swing.JButton();
        jLabel1.setText("jLabel1");
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("设置考试参数");
        FindStat findStat = new FindStat();
    Stat st = new Stat();
    st.setId(1);
    Stat stat = findStat.getStat(st);
    radioBL.setText("单选题比例：");       
    setTitle("设置参数窗体");
    radiojComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "80", "70", "60", "50","40","30","20","10" }));
    radiojComboBox.setSelectedItem(""+stat.getRadio_BL());
    messageJLabel.setText("%");
    moreBL1.setText("多选题比例：");
    morejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "80", "70", "60", "50","40","30","20","10" }));
    morejComboBox.setSelectedItem(""+stat.getMore_BL());
    jLabel2.setText("%");
    judgeBL.setText("判断题比例：");
    judgeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"80", "70", "60", "50","40","30","20","10" }));
    judgeJComboBox.setSelectedItem(""+stat.getJudge_BL());
    signJLabel.setText("%");
    examTime.setText("  考试时间：");
    examTimejTextField.setText(""+stat.getExam_time());
    minutejLabel.setText("分钟");
    radiojLabel.setText("单选题分值：");
    radioMarkjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "8", "10" }));
    radioMarkjComboBox.setSelectedItem(""+stat.getRadio_FS());
    morejLabel.setText("多选题分值：");
    moreMarkjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "8", "10" }));
    moreMarkjComboBox.setSelectedItem(""+stat.getMore_FS());
    judgejLabel.setText("判断题分值：");
    judgeMarkjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "5", "8", "10"}));
    judgeMarkjComboBox1.setSelectedItem(""+stat.getJudge_FS());
        messagejLabel.setText("*注：三种类型题之和必须是100%。");
        okjButton.setText("确定");
        okjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okjButtonActionPerformed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        resetjButton.setText("取消");
        resetjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(radioBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radiojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(moreBL1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(morejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(examTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(judgeBL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(judgeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(examTimejTextField))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(messageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(signJLabel))
                                        .addGap(62, 62, 62)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(judgejLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(judgeMarkjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(radiojLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(radioMarkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(morejLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(moreMarkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(minutejLabel)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(okjButton)
                        .addGap(35, 35, 35)
                        .addComponent(resetjButton)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBL)
                    .addComponent(radiojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageJLabel)
                    .addComponent(radiojLabel)
                    .addComponent(radioMarkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moreBL1)
                    .addComponent(morejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(morejLabel)
                    .addComponent(moreMarkjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judgeBL)
                    .addComponent(judgeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signJLabel)
                    .addComponent(judgejLabel)
                    .addComponent(judgeMarkjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examTimejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutejLabel)
                    .addComponent(examTime))
                .addGap(18, 18, 18)
                .addComponent(messagejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetjButton)
                    .addComponent(okjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

private void okjButtonActionPerformed(java.awt.event.ActionEvent evt) {
	String radioBox = radiojComboBox.getSelectedItem().toString();
	String moreBox = morejComboBox.getSelectedItem().toString();
	String judgeBox = judgeJComboBox.getSelectedItem().toString();
	if((Integer.parseInt(radioBox)+
			Integer.parseInt(moreBox)+Integer.parseInt(judgeBox))!=100){
		JOptionPane.showMessageDialog(this,"题目比例之和必须等于100！" ,"信息对话框", JOptionPane.WARNING_MESSAGE);
		return;
	}
	if(examTimejTextField.getText() == null){
		JOptionPane.showConfirmDialog(this, "没有设置考试时间！",
				"信息对话框", JOptionPane.WARNING_MESSAGE);
	}
	Stat stat = new Stat();
	stat.setId(1);
	stat.setJudge_BL(Integer.parseInt(judgeBox));
	stat.setJudge_FS(Integer.parseInt(judgeMarkjComboBox1.getSelectedItem().toString()));
	stat.setMore_BL(Integer.parseInt(moreBox));
	stat.setExam_time(Integer.parseInt(examTimejTextField.getText()));
	stat.setMore_FS(Integer.parseInt(moreMarkjComboBox.getSelectedItem().toString()));
	stat.setRadio_BL(Integer.parseInt(radioBox));
	stat.setRadio_FS(Integer.parseInt(radioMarkjComboBox.getSelectedItem().toString()));
	FindStat findSta = new FindStat();
	boolean bool = findSta.updateStatDBbean(stat);
	if(bool == true){
		JOptionPane.showMessageDialog(this, "系统参数设置成功！", "信息对话框",JOptionPane.WARNING_MESSAGE);
	}
}

private void resetjButtonActionPerformed(java.awt.event.ActionEvent evt) {
	dispose();
	ControllerFrame controll = new ControllerFrame();
	controll.setVisible(true);
	controll.setBounds(100, 150, 655, 455);
}
private void formWindowClosing(java.awt.event.WindowEvent evt) {
	dispose();
	ControllerFrame controll = new ControllerFrame();
	controll.setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel examTime;
    private javax.swing.JTextField examTimejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judgeBL;
    private javax.swing.JComboBox judgeJComboBox;
    private javax.swing.JComboBox judgeMarkjComboBox1;
    private javax.swing.JLabel judgejLabel;
    private javax.swing.JLabel messageJLabel;
    private javax.swing.JLabel messagejLabel;
    private javax.swing.JLabel minutejLabel;
    private javax.swing.JLabel moreBL1;
    private javax.swing.JComboBox moreMarkjComboBox;
    private javax.swing.JComboBox morejComboBox;
    private javax.swing.JLabel morejLabel;
    private javax.swing.JButton okjButton;
    private javax.swing.JLabel radioBL;
    private javax.swing.JComboBox radioMarkjComboBox;
    private javax.swing.JComboBox radiojComboBox;
    private javax.swing.JLabel radiojLabel;
    private javax.swing.JButton resetjButton;
    private javax.swing.JLabel signJLabel;
    // End of variables declaration//GEN-END:variables

}
